#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbWbp6TRPdEJeuZaHLJkAJOFT6OGGuiUWA/6T302C32TCja/u/cfgp42Kqvj3QSYOObXEYRyfWGMDNvA4I8EPnW15m+1Obx+GX/3Y33l3ccr01gtL0hF8qJ9nmLEkFufBywsXciX2c3+lftJiyj1h7x+KTW75pdlm9O7J/bSPFywIMK4gPvRf0FxLGLbRWqubdWLi25yX0OG/VJKlZqOu21iyg3enGCCpbln8X4KSm40ho+APv+978M7VS/i2iSzh887mPanyJUxkXoc6HV6PzJ9b4XCrW5muwkdCaCYppumUXzFl6xp2wOB3EJ5HT1WjuoRey9O/Y8PMK5aOTA8J5Rgq4OXV67MaU2rYdPD5Eb/ifDIUQ2yUwOHGSKkwTir74k2TBuVYBG+RwyQ0F1qfTZICy0aPH9iw8p87IzTpvDoyDy/zTd4F/Xi5irqzZ/E8BHQR2jTrVZC+2hN6zgqndU4iCAV76+JvZpauUxjtUT5fAni9UMv/9HSagU5Tr59KFQUrT5YRFCnQK/F9MQXHL3Ux6nkyOfKSYcz+ofF9r9rlHZ7cVwtu9p2sFs9myZhlwzs8nxTDCIPLBoAe5I7DoMQlFYiL5Iab2Gnp8fQjmcSs0PyXV6NjyKroKyLb9VXTo5+a8zf0ytpKu8pXKYCQhB7vU+L1UVFO3UOO8WpRfDw== alexlinux@compute-vm-2-1-10-hdd-1764726993335
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
